### ISSUE TITLE
debian release

### ISSUE THREAD

**Issue by Timple** [mrath/mobile_robot_simulator#1]
I know this repository hasn't been updated in a while, but the code is still valid.

Are you interested in creating a [debian release](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Releasing_Your_Packages)?

**Comment by Timple** [comment]
@mrath Would you mind if I fork and release your code for melodic and noetic?

Qui tacet consentire videtur, ubi loqui debuit ac potuit

**Comment by Timple** [comment]
FYI: I've released this repo and one can now `apt install ros-<rosdistro>-mobile-robot-simulator` e.g. `apt install ros-melodic-mobile-robot-simulator`

**Comment by mrath** [comment]
hey @Timple! So sorry for the late reply, don't check here often. 
Everything is fine with me, I'm glad someone is using it. Did you release this repo or a fork? Do you need me to do anything  -accept pull request, etc?

**Comment by Timple** [comment]
No worries, thanks for creating the package :slightly_smiling_face:. Haven't found an alternative yet which simply creates `odom` & `TF` from `cmd_vel`. Very useful in really quick simulations for unit-testing.

I've released our branch from the PR. Because without installing the targets you cannot create debian files from the executables.
